'use strict';

const fs = require('fs');
const dotenv = require("dotenv");
const { GoogleSpreadsheet } = require('google-spreadsheet');

dotenv.config();


/*
 * Functions to process the report
 */

function getManifest() {
    console.log(`Reading manifest from environment variable...`);
    return JSON.parse(process.env.MANIFEST);
}

function getReport(manifestEntry) {

    console.log(`Reading JSON file: ${manifestEntry.jsonPath}`);
    let rawJson = fs.readFileSync( manifestEntry.jsonPath );
    let lhJson = JSON.parse(rawJson);

    console.log(`JSON loaded: ${lhJson["requestedUrl"]}`);
    return lhJson;
}

/*
 * Functions to upload to Google Sheets
 */

async function uploadReport(doc, report) {
    const requestedUrl = new URL(report.requestedUrl);
    const requestedHostname = requestedUrl.hostname;

    const sheet = loadSheet(doc, requestedHostname);
}

async function loadSheet(doc, requestedHostname) {
    await doc.loadInfo();
    if (!(requestedHostname in doc.sheetsByTitle)) {
        await doc.addSheet({
            title: requestedHostname,
        });
    }

    await doc.loadInfo();
    return doc.sheetsByTitle[requestedHostname];
}

async function initGSheet() {
    console.log('Initializing Google Sheets...');
    const doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID);

    console.log('Authenticating Google Sheets...');
    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
        private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
    })
    
    console.log('Loading Google Sheets...');
    await doc.loadInfo(); // loads document properties and worksheets

    console.log(`Loaded ${doc.title}`);
    return doc;
}

/*
 * Run
 */

const main = async () => {
    const doc = await initGSheet();
    const manifest = getManifest();
    const reports = manifest.map( getReport );

    for (const report in reports) {
        await uploadReport(doc, report);
    }
    
    const sheet = doc.sheetsByIndex[0]; // or use doc.sheetsById[id] or doc.sheetsByTitle[title]
    console.log(sheet.title);
    console.log(sheet.rowCount);
};

main();
