name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        id: audit
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://central.co.th
            https://kingpower.com
            https://monline.com
            https://shopee.co.th
            https://lazada.co.th
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Process Lighthouse Report
        run: |
          npm install &&
          node ./postAudit.js
        env:
          RESULTPATH: ${{ steps.audit.outputs.resultsPath }}
          ASSERTIONRESULTS: ${{ steps.audit.outputs.assertionResults }}
          MANIFEST: ${{ steps.audit.outputs.manifest }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_PRIVATE_KEY: ${{ secrets.GOOGLE_PRIVATE_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}

