name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d.%H')"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://central.co.th
            https://kingpower.com
            https://monline.com
            https://shopee.co.th
            https://lazada.co.th
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
          resultsPath: ~/${{ steps.date.outputs.date }}/
      - name: Debug Lighthouse
        id: date
        run: pwd && ls -R ./
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      #     cache: 'npm'
      # - run: npm install